name: mobile_test
description: "Used to execute package:unix_api tests on Android and iOS"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  tests:
    path: ../tests
