# See https://github.com/google/mono_repo.dart
sdk:
 - dev
 - pubspec

stages:
- analyze_and_format:
  - analyze: --fatal-infos
- unit_test:
  - test: --test-randomize-ordering-seed=random --platform vm
    os:
    - linux
    - macos
    - windows
  - test: --test-randomize-ordering-seed=random --platform chrome
  - test: --test-randomize-ordering-seed=random --platform chrome -c dart2wasm
