name: io_file
description: A starting point for Dart libraries or applications.
version: 0.1.0-wip
repository: https://github.com/dart-lang/labs/tree/main/pkgs/io_file

environment:
  sdk: ^3.7.0

dev_dependencies:
  dart_flutter_team_lints: ^3.4.0
  test: ^1.24.0
