name: io_file
description: A starting point for Dart libraries or applications.
version: 0.1.0-wip
repository: https://github.com/dart-lang/labs/tree/main/pkgs/io_file
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  ffi: ^2.1.4
  stdlibc:
    git:
      # TODO(brianquinlan): Change this to a released version.
      url: https://github.com/canonical/stdlibc.dart.git
  win32:
    git:
      # TODO(brianquinlan): Change this to a released version.
      url: https://github.com/halildurmus/win32.git
      path: packages/win32

dev_dependencies:
  dart_flutter_team_lints: ^3.4.0
  path: ^1.9.1
  test: ^1.24.0
