name: gcloud
version: 0.0.1-dev
description: Dart gcloud APIs
environment:
  sdk: '>=1.5.0 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  googleapis: '>=0.2.0 <0.4.0'
  googleapis_beta: '>=0.3.0 <0.5.0'
  http: '>=0.11.0 <0.12.0'
dev_dependencies:
  http_parser: '>=0.0.2+5 <0.1.0'
  googleapis_auth: any
  mime: '>=0.9.0+3 <0.10.0'
  unittest: '>=0.11.0 <0.12.0'
transformers:
- $dart2js:
    $include: []
