name: gcloud
version: 0.0.1-dev
description: Dart gcloud APIs
environment:
  sdk: '>=1.5.0 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  http:  '>=0.11.0 <0.12.0'
  googleapis_beta: '>=0.1.0 <0.2.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
