name: appengine
version: 0.1.0
author: Dart Team
dependencies:
  cloud_datastore:
    path: ../cloud_datastore
  fixnum: any
  http_server: any
  memcache:
    path: ../memcache
  path: any
  protobuf: any
  yaml: any
dev_dependencies:
  unittest: any
