name: appengine
version: 0.1.0
author: Dart Team
dependencies:
  fixnum: any
  memcache:
    path: ../memcache
  protobuf: any
  yaml: any
  cloud_datastore:
    path: ../cloud_datastore
dev_dependencies:
  unittest: any
