name: appengine
version: 0.3.0
author: Dart Team <misc@dartlang.org>
description: Support for using Dart as a custom runtime on Google App Engine Managed VMs
homepage: https://www.dartlang.org/cloud
environment:
  sdk: '>=1.5.0 <2.0.0'
dependencies:
  gcloud: '>=0.1.2 <0.3.0'
  googleapis_auth: '>=0.1.1 <0.3.0'
  fixnum: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.2 <0.10.0'
  memcache: '>=0.2.0 <0.3.0'
  path: '>=1.2.0 <2.0.0'
  protobuf: '>=0.3.3 <0.4.0'
  logging: '>=0.9.3 <0.10.0'

dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
