name: appengine
version: 0.1.0
author: Dart Team
environment:
  sdk: '>=1.4.0 <2.0.0'
dependencies:
  cloud_datastore:
    git:
      url: https://github.com/dart-lang/cloud_datastore
      ref: v0.1
  fixnum: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.2 <0.10.0'
  memcache:
    git:
      url: https://github.com/dart-lang/memcache
      ref: v0.1
  path: '>=1.2.0 <2.0.0'
  protobuf: '>=0.3.3 <0.4.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
