name: appengine
version: 0.3.3
author: Dart Team <misc@dartlang.org>
description: Support for using Dart as a custom runtime on Google App Engine Managed VMs
homepage: https://www.dartlang.org/cloud
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  fixnum: '>=0.9.0 <0.11.0'
  gcloud: '>=0.1.2 <0.3.0'
  googleapis_auth: '>=0.1.1 <0.3.0'
  http_server: '^0.9.2'
  logging: '>=0.9.3 <0.12.0'
  memcache: '^0.2.0'
  path: '^1.2.0'
  protobuf: '^0.5.0'
dev_dependencies:
  test: '^0.12.0'
