name: appengine
version: 0.1.0
author: Dart Team
environment:
  sdk: '>=1.4.0 <2.0.0'
dependencies:
  cloud_datastore: any
  fixnum: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.2 <0.10.0'
  memcache: any
  path: '>=1.2.0 <2.0.0'
  protobuf: '>=0.3.3 <0.4.0'
dev_dependencies:
  matcher: '>=0.10.0 <0.11.0'
  unittest: '>=0.11.0 <0.12.0'
dependency_overrides:
  cloud_datastore:
    path: ../cloud_datastore
  memcache:
    path: ../memcache
