name: package:io_file

permissions: read-all

on:
  # Run CI on pushes to the main branch, and on PRs against main.
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/io_file.yml'
      - 'pkgs/io_file/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/io_file.yml'
      - 'pkgs/io_file/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

defaults:
  run:
    working-directory: pkgs/io_file

jobs:
  analyze_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: stable
      - run: dart pub get
      - run: dart analyze --fatal-infos
      - run: dart format --output=none --set-exit-if-changed .

  android-vm-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/io_file/mobile_test
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff
        with:
          channel: 'stable'
      - id: install
        name: Install dependencies
        run: flutter pub get
      - run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - uses: reactivecircus/android-emulator-runner@62dbb605bba737720e10b196cb4220d374026a6d
        if: always() && steps.install.outcome == 'success'
        with:
          api-level: 21 
          disable-animations: true
          arch: x86_64
          target: default
          script: cd pkgs/io_file/mobile_test && flutter test --timeout=1200s integration_test/

  desktop-vm-test:
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, dev]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: ${{ matrix.sdk }}

      - run: dart test --test-randomize-ordering-seed=random --platform vm

  desktop-vm-benchmark:
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - name: 🪑 Run benchmarks
        run: dart run benchmarks/read_as_bytes.dart

  web-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: stable

      - run: dart test --test-randomize-ordering-seed=random --platform chrome
